#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged to format and lint staged files
npm run pre-commit

# Run type checking
npm run type-check

# Run tests for staged files
npm run test:unit 